### ISSUE TITLE
Windows problem with crypto

### ISSUE THREAD

**Issue by macekboris** [R0rt1z2/realme-ota#10]
Greetings.

Since I'm using the win python 3.9
upgrade pycryptodome
clone git, have problem guess with crypto module or crypto.py in utils or so kind environmental problem.

So far been able to bypass it with 
sys.modules['Crypto'] = crypto

But not now ...

Previous versions have runned ok, but don't know how to fix this one ...

Looking forward for feedback to solve it.

`C:\Users\userx\Documents\Realme 8 Pro\OTA\realme-ota\realme_ota>py main.py
Traceback (most recent call last):
  File "C:\Users\userx\Documents\Realme 8 Pro\OTA\realme-ota\realme_ota\main.py", line 9, in <module>
    from utils import crypto
  File "C:\Users\userx\Documents\Realme 8 Pro\OTA\realme-ota\realme_ota\utils\crypto.py", line 7, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\userx\Documents\Realme 8 Pro\OTA\realme-ota\realme_ota\main.py", line 14, in <module>
    from realme_ota.utils import crypto
  File "C:\Users\userx\AppData\Local\Programs\Python\Python39\lib\site-packages\realme_ota\utils\crypto.py", line 7, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

C:\Users\userx\Documents\Realme 8 Pro\OTA\realme-ota\realme_ota>`

Uninstall Crypto and install pycryptodome also doesn't work.

**Comment by R0rt1z2** [comment]
It works fine here (with Windows as well). The only thing I can suggest you is to re-install your Python environment or (try to) force re-install the *pycryptodome* (pip) package with `pip3 install --upgrade --force-reinstall pycryptodome`.

**Comment by R0rt1z2** [comment]
May I ask why are you using `py` instead of `python3` (or `python` if you only have python3)? I just tried to run the tool with `py` and I also had problems with pip packages.

**Comment by macekboris** [comment]
I'm using python just for few things or simple programs.

To be hohnest the shorter the batch the better.
...Habbit after all.
