### ISSUE TITLE
RMX3361

### ISSUE THREAD

**Issue by yuxuxin233** [R0rt1z2/realme-ota#14]
![QQ图片20220223150016](https://user-images.githubusercontent.com/73999603/155274216-37471836-9db0-4865-b639-95b1209b1568.png)
realme-ota RMX3361 RMX3361_11.C.01_001_202202101618 3 -r 1

**Comment by yuxuxin233** [comment]
realme-ota RMX3361 RMX3361_11.A.01_001_202202101618 3 -r 1

**Comment by R0rt1z2** [comment]
Duplicate of https://github.com/R0rt1z2/realme-ota/issues/5.
