### ISSUE TITLE
RMX3478错误

### ISSUE THREAD

**Issue by yuxuxin233** [R0rt1z2/realme-ota#24]
<img width="927" alt="屏幕截图 2022-06-12 170255" src="https://user-images.githubusercontent.com/73999603/173225797-b5144dc3-57ff-4d9f-a06d-c9f4544e0667.png">
<img width="927" alt="屏幕截图 2022-06-12 170237" src="https://user-images.githubusercontent.com/73999603/173225806-f2f3964d-3aa0-4cd2-8bf4-9f3889e10755.png">
<img width="927" alt="屏幕截图 2022-06-12 170219" src="https://user-images.githubusercontent.com/73999603/173225809-4bbf9254-d6a8-4b09-a490-38da0011217d.png">

**Comment by R0rt1z2** [comment]
> <img alt="屏幕截图 2022-06-12 170255" width="927" src="https://user-images.githubusercontent.com/73999603/173225797-b5144dc3-57ff-4d9f-a06d-c9f4544e0667.png">
> 
> <img alt="屏幕截图 2022-06-12 170237" width="927" src="https://user-images.githubusercontent.com/73999603/173225806-f2f3964d-3aa0-4cd2-8bf4-9f3889e10755.png">
> 
> <img alt="屏幕截图 2022-06-12 170219" width="927" src="https://user-images.githubusercontent.com/73999603/173225809-4bbf9254-d6a8-4b09-a490-38da0011217d.png">

As the tool says, you must provide the `nv_id` parameter. In your case it seems to be `10010111` so you would need to run the tool with `realme-ota RMX3478 RMX3478_11.A.38_0000_000000000000 3 10010111 -r 1`.
