### ISSUE TITLE
Request support to add deviceId parameter

### ISSUE THREAD

**Issue by hanajoruno** [R0rt1z2/realme-ota#30]
The deviceid exists in both the headers and data of the request body, this data is obtained by sha256 encryption of the data in the third line in /data/system/openid_config.xml called "guid".
In China, CBT and OBT and MP are released in parallel. So if you want to obtain the CBT or OBT package, you need to provide deviceid.
These two deviceids are different，the deviceid in data is guid, and the deviceid in headers is guid for sha256 encryption

**Comment by R0rt1z2** [comment]
Closing as per https://github.com/R0rt1z2/realme-ota/pull/31
