### ISSUE TITLE
Cannot run directly on Windows

### ISSUE THREAD

**Issue by crazo7924** [R0rt1z2/realme-ota#35]
Windows users have to run
python .\realme-ota\main.py

**Comment by R0rt1z2** [comment]
> Windows users have to run python .\realme-ota\main.py

```powershell
Invoke-WebRequest https://cdn.r0rt1z2.com/realme-ota/Install.ps1 | Invoke-Expression
```
.. should automatically set up everything so you don't really need to manually call the script.
