### ISSUE TITLE
Unable to install realme-ota on windows

### ISSUE THREAD

**Issue by aruto768** [R0rt1z2/realme-ota#37]
![Screenshot 2022-12-06 110830](https://user-images.githubusercontent.com/92055052/205895723-26dac5d1-e499-4b2b-a97f-e4165469e049.png)

Using Terminal run as admin, new tab PowerShell put this

# (Requires privilegies)
Invoke-WebRequest https://cdn.r0rt1z2.com/realme-ota/Install.ps1 | Invoke-Expression

i got error, like that

**Comment by JunMuraKami** [comment]
I'm facing the same issue.
The URL doesn't seem to exist.

`Invoke-WebRequest -Uri https://gist.githubusercontent.com/R0rt1z2/9b4600b5bb11d0750bdcebea04374c63/raw/b4df9d6ff725904b2115bb8353bd1fcb6de24b5b/realme-ota.bat -Outfile realme-ota.bat`

**Comment by R0rt1z2** [comment]
The wrapper wasn't being downloaded at all, it should work now, please try again.
