### ISSUE TITLE
Hey i need help

### ISSUE THREAD

**Issue by binhvo7794** [R0rt1z2/realme-ota#39]
After download components, i convert system.new.dat.br to system.img using brotli and sdat2img, but the system.img can't be flash via twrp or fastboot, how to convert it to normal img file
![Screenshot_2022-12-18-02-13-01-95_db51e592e420a9871f4a37915a68789b](https://user-images.githubusercontent.com/66165345/208277139-e421dac4-b95f-4efb-ac1b-474a6d01ee0b.jpg)

**Comment by R0rt1z2** [comment]
[Try with `simg2img` or `img2simg`.](https://github.com/anestisb/android-simg2img).
