### ISSUE TITLE
How can I fix Response status mismatch, expected '200' got '203' (otaVersion parse exception)?

### ISSUE THREAD

**Issue by k0m12** [R0rt1z2/realme-ota#43]
![スクリーンショット 2023-02-09 203455](https://user-images.githubusercontent.com/124884913/217802733-ce77110e-7526-4cdf-9367-f04532467a30.png)

How can I fix Response status mismatch, expected '200' got '203' (otaVersion parse exception)?
I would like to get a link to the OTA file for RMX3361, but cannot get it with this error.
What should I do?

**Comment by Hryniuk1** [comment]
RUI 2: `realme-ota -r 1 RMX3361 RMX3361_11.A.01_0000_202200000000 2 10011000`
RUI 3: `realme-ota -r 1 RMX3361 RMX3361_11.C.01_0000_202200000000 3 10011000`
RUI 4: `realme-ota -r 1 RMX3361 RMX3361_11.F.01_0000_202200000000 4 10011000`

**Comment by rapperskull** [comment]
Looks like a typo
