### ISSUE TITLE
Now response always get '200' got '304' (no modify)!

### ISSUE THREAD

**Issue by pokobunhsu** [R0rt1z2/realme-ota#49]
This is from RMX3370
Command: realme-ota RMX3370 RMX3370_11.A.00_0000_000000000000 4

Response status mismatch, expected '200' got '304' (no modify)!

**Comment by rapperskull** [comment]
Works for me. It might be a problem related to your location. Try to set the `ALL_PROXY` environment variable to a proxy in another country.
