### ISSUE TITLE
setup.py: Illegal CR character (^M)

### ISSUE THREAD

**Issue by Hakimi0804** [R0rt1z2/realme-ota#6]
Hi, it seems like setup.py contains illegal CR character which makes the shebang pretty pointless
```
[hakimi@fedora realme-ota]$ ./setup.py 
bash: ./setup.py: /usr/bin/python3^M: bad interpreter: No such file or directory
[hakimi@fedora realme-ota]$ 
```
this can be removed with `sed -i 's/\r//' setup.py`

**Comment by R0rt1z2** [comment]
Thanks, pushed the fix with your authorship
